version: '3.9'
services:
  ui:
    build:
      context: .
    ports:
      - "8080:80"
    networks:
      - app-network

  bff:
    build:
      context: ../BFF
    ports:
      - "3000:3000"
    networks:
      - app-network

  #RAG:
  #  build:
  #    context: ../RAG
  #  ports:
  #    - "9000:8080"
  #  networks:
  #    - app-network

networks:
  app-network:
    driver: bridge
